language: cpp

env:
  - CMAKE_BUILD_TYPE=Debug

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

sudo: required

dist: trusty

before_install:
  # in case the default sources yield hashsum errors ...
  # from https://github.com/The-Compiler/qutebrowser/blob/master/scripts/dev/ci_install.py#L71-L74
  - if [ "$TRAVIS_OS_NAME" = linux ]; then if sudo apt-get update -qq ; then : else sudo sed -i 's/us-central1\.gce/us/' /etc/apt/sources.list ; sudo apt-get update -qq ; fi ; fi
  - if [ "$TRAVIS_OS_NAME" = linux ]; then sudo apt-get install -qq libboost-dev libboost-test-dev libboost-system-dev libboost-filesystem-dev ; fi

# install:

before_script:
  - uname -a
  - mkdir build
  - cd build
  # PWD -> build
  - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE ..

# PWD -> build
script: make -j1 ixxx_static ixxx check
