language: cpp

env:
  - CMAKE_BUILD_TYPE=Debug

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

sudo: required

dist: trusty

# before_install:

# install:

before_script:
  - mkdir build
  - cd build
  # PWD -> build
  - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE ..

# PWD -> build
script: make -j1 ixxx_static ixxx check
