language: cpp

env:
  - CMAKE_BUILD_TYPE=Debug

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

sudo: required

dist: trusty

before_install:
  - if [ "$TRAVIS_OS_NAME" = linux ]; then sudo apt-get update -qq ; fi
  - if [ "$TRAVIS_OS_NAME" = linux ]; then sudo apt-get install -qq libboost-dev libboost-test-dev ; fi

# install:

before_script:
  - uname -a
  - mkdir build
  - cd build
  # PWD -> build
  - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE ..

# PWD -> build
script: make -j1 ixxx_static ixxx check
